'use client';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useInvoiceStore } from '@/store/invoiceStore';
import { useAuthStore } from '@/store/authStore';
import { MOCK_INVOICES, formatCurrency, formatDate } from '@/lib/mockData';
import { PayButton } from '@/components/payment/PayButton';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { Card } from '@/components/ui/Card';
import { Spinner } from '@/components/ui/Spinner';
import { ArrowLeft, Download, FileText, Calendar, User, Hash } from 'lucide-react';
import toast from 'react-hot-toast';
import Link from 'next/link';
import { Invoice } from '@/types';

export default function InvoiceDetailPage() {
  const params  = useParams();
  const router  = useRouter();
  const { user, role } = useAuthStore();
  const { updateInvoiceStatus } = useInvoiceStore();

  const [invoice, setInvoice]           = useState<Invoice | null>(null);
  const [notFound, setNotFound]         = useState(false);
  const [downloading, setDownloading]   = useState(false);

  useEffect(() => {
    const id  = Array.isArray(params.id) ? params.id[0] : params.id;
    const inv = MOCK_INVOICES.find((i) => i.id === id);

    if (!inv) { setNotFound(true); return; }

    // ── Security: clients can only see their own invoices ───────────────────
    if (role === 'client' && user && inv.clientId !== user.uid) {
      router.replace('/403');
      return;
    }

    setInvoice(inv);
  }, [params.id, user, role, router]);

  async function handleDownloadPDF() {
    if (!invoice || downloading) return;
    setDownloading(true);

    const toastId = toast.loading('Generating PDF...', {
      style: { background: '#0F1F3D', color: '#E2E8F0', border: '1px solid #1E3A5F' },
    });

    try {
      // Try the API route first
      const res = await fetch(`/api/invoices/${invoice.id}/pdf`, {
        headers: { 'Accept': 'application/pdf' },
      });

      if (res.ok) {
        const blob = await res.blob();
        const url  = URL.createObjectURL(blob);
        const a    = document.createElement('a');
        a.href     = url;
        a.download = `${invoice.invoiceNumber}.pdf`;
        a.click();
        URL.revokeObjectURL(url);
        toast.success('PDF downloaded successfully!', { id: toastId });
      } else {
        throw new Error('PDF service unavailable');
      }
    } catch {
      // Demo fallback: generate a simple text-based PDF stub
      await new Promise((r) => setTimeout(r, 1500));
      const content = `
VAULTPAY FINANCIAL CORE
Invoice: ${invoice.invoiceNumber}
Date: ${formatDate(invoice.createdAt)}
Due: ${formatDate(invoice.dueDate)}

BILL TO:
${invoice.clientName}
${invoice.clientEmail}

DESCRIPTION:
${invoice.description ?? 'Professional Services'}

AMOUNT DUE: ${formatCurrency(invoice.amount)}
STATUS: ${invoice.status}

---
This invoice was generated by VaultPay Financial Core.
Secured by 256-bit TLS encryption.
      `.trim();

      const blob = new Blob([content], { type: 'text/plain' });
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement('a');
      a.href     = url;
      a.download = `${invoice.invoiceNumber}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success('Invoice downloaded (demo mode)', { id: toastId });
    } finally {
      setDownloading(false);
    }
  }

  if (notFound) {
    return (
      <div className="text-center py-20">
        <p className="text-vault-muted">Invoice not found.</p>
        <Link href="/client/invoices" className="text-vault-blue-lt mt-2 block hover:underline">
          ← Back to invoices
        </Link>
      </div>
    );
  }

  if (!invoice) {
    return (
      <div className="flex items-center justify-center py-20">
        <Spinner size="lg" />
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-3xl animate-fade-in">
      {/* Back */}
      <Link
        href="/client/invoices"
        className="inline-flex items-center gap-2 text-vault-muted text-sm hover:text-vault-subtle transition-colors"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Invoices
      </Link>

      {/* Invoice header */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <h1 className="text-2xl font-bold text-vault-text font-mono">{invoice.invoiceNumber}</h1>
            <StatusBadge status={invoice.status} />
          </div>
          <p className="text-vault-muted text-sm">
            Issued {formatDate(invoice.createdAt)}
            {invoice.paidAt && ` · Paid ${formatDate(invoice.paidAt)}`}
          </p>
        </div>

        {/* Amount */}
        <div className="text-right">
          <p className="text-vault-muted text-xs font-semibold uppercase tracking-wider mb-1">Amount Due</p>
          <p className="text-4xl font-bold font-mono text-vault-text">{formatCurrency(invoice.amount)}</p>
        </div>
      </div>

      {/* Details grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <Card>
          <p className="text-vault-muted text-xs font-semibold uppercase tracking-wider mb-4">Client Information</p>
          <div className="space-y-3">
            <div className="flex items-center gap-3">
              <User className="w-4 h-4 text-vault-muted flex-shrink-0" />
              <div>
                <p className="text-vault-text text-sm font-semibold">{invoice.clientName}</p>
                <p className="text-vault-muted text-xs">{invoice.clientEmail}</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <Hash className="w-4 h-4 text-vault-muted flex-shrink-0" />
              <div>
                <p className="text-vault-muted text-xs">Client ID</p>
                <p className="text-vault-subtle text-xs font-mono">{invoice.clientId}</p>
              </div>
            </div>
          </div>
        </Card>

        <Card>
          <p className="text-vault-muted text-xs font-semibold uppercase tracking-wider mb-4">Invoice Details</p>
          <div className="space-y-3">
            <div className="flex items-center gap-3">
              <Calendar className="w-4 h-4 text-vault-muted flex-shrink-0" />
              <div>
                <p className="text-vault-muted text-xs">Due Date</p>
                <p className="text-vault-text text-sm font-semibold">{formatDate(invoice.dueDate)}</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <FileText className="w-4 h-4 text-vault-muted flex-shrink-0" />
              <div>
                <p className="text-vault-muted text-xs">Description</p>
                <p className="text-vault-subtle text-sm">{invoice.description ?? 'Professional Services'}</p>
              </div>
            </div>
          </div>
        </Card>
      </div>

      {/* Amount breakdown */}
      <Card>
        <p className="text-vault-muted text-xs font-semibold uppercase tracking-wider mb-4">Payment Summary</p>
        <div className="space-y-2">
          <div className="flex items-center justify-between py-2 border-b border-vault-border">
            <span className="text-vault-subtle text-sm">{invoice.description ?? 'Professional Services'}</span>
            <span className="text-vault-text font-mono font-semibold">{formatCurrency(invoice.amount)}</span>
          </div>
          <div className="flex items-center justify-between py-2 border-b border-vault-border">
            <span className="text-vault-muted text-sm">Tax (0%)</span>
            <span className="text-vault-muted font-mono">$0</span>
          </div>
          <div className="flex items-center justify-between py-3">
            <span className="text-vault-text font-semibold">Total Due</span>
            <span className="text-2xl font-bold font-mono text-vault-text">{formatCurrency(invoice.amount)}</span>
          </div>
        </div>
      </Card>

      {/* Actions */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
        {/* Pay button — only visible for unpaid invoices to clients */}
        {invoice.status !== 'Paid' && (
          <PayButton invoice={invoice} />
        )}

        {/* Download PDF */}
        <button
          id="download-pdf-btn"
          onClick={handleDownloadPDF}
          disabled={downloading}
          className="
            flex items-center justify-center gap-2.5
            px-6 py-3.5 rounded-xl font-semibold text-sm
            border border-vault-border text-vault-subtle
            hover:border-vault-blue/40 hover:text-vault-text hover:bg-vault-blue/5
            active:scale-[0.98] transition-all duration-200
            disabled:opacity-50 disabled:cursor-not-allowed
          "
        >
          {downloading ? (
            <><Spinner size="sm" /> Generating PDF...</>
          ) : (
            <><Download className="w-4 h-4" /> Download PDF</>
          )}
        </button>
      </div>

      {/* Status history */}
      {invoice.paidAt && (
        <Card>
          <p className="text-vault-muted text-xs font-semibold uppercase tracking-wider mb-3">Payment History</p>
          <div className="flex items-center gap-3">
            <div className="w-2 h-2 rounded-full bg-vault-green" />
            <div>
              <p className="text-vault-green text-sm font-semibold">Payment Received</p>
              <p className="text-vault-muted text-xs">{formatDate(invoice.paidAt)} · {formatCurrency(invoice.amount)}</p>
            </div>
          </div>
        </Card>
      )}
    </div>
  );
}
